### ISSUE TITLE
Legato 側のサーバプロセスの作成

### ISSUE THREAD

**Issue by Asteriskx** [Veloce-dev/Veloce#3]

**Comment by marihachi** [comment]
このリポジトリではやらなくても良いかも
どちらかというと、Veloceのプロセス通信の仕様を使ってLegato側で実装する感じな気がする

**Comment by marihachi** [comment]
このプロジェクトのゴールは、
統一されたAPIで曲情報をやり取りするプロトコル及びライブラリの作成
辺りになると思ってるんだけど、どう？

**Comment by Asteriskx** [comment]
あ、issue 建てるプロジェクト間違えてた。。
認識アッテルヨー
